### ISSUE TITLE
rC3 link to recording is broken

### ISSUE THREAD

**Issue by heidemn** [thomasfricke/training-kubernetes-security#2]
Thanks for presenting at rC3 and for sharing the [slides](https://pretalx.c3voc.de/rc3-2021-cbase/talk/GDMAKJ/).

Is the recording also available somewhere?
Going [here](https://fahrplan.events.ccc.de/rc3/2021/Fahrplan/#c7e38a83-d930-5cb5-aab4-b3f37b956040) and clicking on "recording" gets me a 404.
I only found this recording of an older presentation: https://www.youtube.com/watch?v=0_AnFIBhqlk

Thanks!

**Comment by schnells** [comment]
Are you looking for https://media.ccc.de/v/rc3-2021-cbase-247-hacking-containers-ku / https://www.youtube.com/watch?v=bKn1aCHwfy4 ?

**Comment by heidemn** [comment]
Yes - thanks!
